version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: recruitment_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-recruitment}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: recruitment_api
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    env_file:
      - .env.example # Usando params de dev puro para subir simples
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    tty: true
    stdin_open: true
    volumes:
      - .:/app

volumes:
  pgdata:
